
main:
	gcc main.c -I../include -o solution

clean:
	rm -f solution

all: clean main

run: clean main
	./solution


p2:
	gcc part_2.c -I../include -o solution_2

clean_2:
	rm -f solution_2

all_2: clean_2 p2

r2: clean_2 p2
	./solution_2